
CREATE TABLE IF NOT EXISTS REVIEWS
(
  id        INT AUTO_INCREMENT PRIMARY KEY,
  productId INT,
  review    TEXT
);
ALTER TABLE REVIEWS
ADD CONSTRAINT REVIEW_PRODUCT_ID_FK
FOREIGN KEY (productId) REFERENCES PRODUCTS(id);