CREATE TABLE IF NOT EXISTS COMMENTS
(
  id        INT AUTO_INCREMENT PRIMARY KEY,
  reviewId INT,
  comment    TEXT
);
ALTER TABLE COMMENTS
ADD CONSTRAINT COMMENT_REVIEW_ID_FK
FOREIGN KEY (reviewId) REFERENCES PRODUCTS(id);